apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend
spec:
  selector:
    matchLabels:
      app: udagram-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
        - name: udagram-frontend
          image: haylemichealberihun/udagram-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "1024Mi"
              cpu: 500m
            requests:
              cpu: 200m
          envFrom:
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret
            - configMapRef:
                name: env-configmap
