name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to dockerhub
      env:
        USER: ${{secrets.DOCKERHUB_UNAME}}
        PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: docker login -u $USER -p $PASSWORD
    - name: Build the Docker image
      run: docker-compose -f docker-compose-build.yaml build --parallel
    - name: Dockerpush reverseproxy
      run: docker push ${{secrets.DOCKERHUB_USER}}/reverseproxy 
    - name: Dockerpush frontend
      run: docker push ${{secrets.DOCKERHUB_USER}}/udagram-frontend
    - name: Dockerpush api-user
      run: docker push ${{secrets.DOCKERHUB_USER}}/udagram-api-user
    - name: Dockerpush api-feed
      run: docker push ${{secrets.DOCKERHUB_USER}}/udagram-api-feed
